config/routes.rb
EveMailGateway::Application.routes.draw do

  root 'static_pages#home'

  resources :users, :controller => 'users', :only => [:show, :new, :create]
  resources :accounts
  resources :characters, :controller => 'characters', :only => [:show]

  resource  :session, :controller => 'sessions', :only => [:create]

  

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                 :integer          not null, primary key
#  first_name         :string(255)      not null
#  last_name          :string(255)      not null
#  email              :string(255)      not null
#  created_at         :datetime
#  updated_at         :datetime
#  encrypted_password :string(128)
#  confirmation_token :string(128)
#  remember_token     :string(128)
#

class User < ActiveRecord::Base
  include Clearance::User

  has_many :accounts, dependent: :destroy
  has_many :characters, through: :accounts

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
  def show
    begin
      @user = User.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to "/404.html"
    end
  end

  # CNK needed to have the method in this file or I get the parent's user_from_params method
  def create
    super
  end

  # def edit
  #   @user = user_from_params
  #   render :template => 'users/new'
  # end

  # def update
  #   @user = user_from_params

  #   if @user.save
  #     redirect_back_or url_after_create
  #   else
  #     render :template => 'users/new'
  #   end
  # end

  private
    def user_from_params
      user_params = params[:user] || Hash.new
      first_name = user_params.delete(:first_name)
      last_name = user_params.delete(:last_name)
      email = user_params.delete(:email)
      password = user_params.delete(:password)
      
      Clearance.configuration.user_model.new(user_params).tap do |user|
        user.first_name = first_name
        user.last_name = last_name
        user.email = email
        user.password = password
      end
    end

end

app/views/users/_form.html.erb
<div class='text-field'>
  <%= form.label :first_name %>
  <%= form.text_field :first_name %>
</div>

<div class='text-field'>
  <%= form.label :last_name %>
  <%= form.text_field :last_name %>
</div>

<div class='text-field'>
  <%= form.label :email %>
  <%= form.text_field :email, :type => 'email' %>
</div>

<div class='password-field'>
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/edit.html.erb
<div id='clearance' class='sign-up'>
  <h2>Edit your information</h2>

  <%= form_for @user do |form| %>
    <%= render :partial => '/users/form', :object => form %>

    <div class='submit-field'>
      <%= form.submit %>
    </div>

  <% end %>
</div>

app/views/users/show.html.erb
<h1><%= "#{@user.first_name} #{@user.last_name}" %></h1>

<p>
Your in game mail will be forwarded to: <%= mail_to @user.email %>
</p>


<ul>
<%= render @user.characters %>
</ul>

<p><%= link_to "Add an account", new_account_path %></p>